standardColumns <- c("a.canonical",
                     "b.canonical",
                     "relation",
                     "bidirectional",
                     "detectionMethod",
                     "pmid",
                     "a.organism",
                     "b.organism",
                     "a.common",
                     "a.canonicalIdType",
                     "b.common",
                     "b.canonicalIdType",
                     "cellType",
                     "a.modification",
                     "a.cellularComponent",
                     "b.modification",
                     "b.cellularComponent",
                     "provider",
                     "comment")

recognized.canonical.idTypes <- c("entrezGeneID", "recon2ReactionID", "reconMetabolite");
