standardColumns <- c("a.id",
                     "b.id",
                     "relation",
                     "bidirectional",
                     "detectionMethod",
                     "pmid",
                     "a.organism",
                     "b.organism",
                     "a.name",
                     "a.idType",
                     "b.name",
                     "b.idType",
                     "cellType",
                     "a.modification",
                     "a.cellularComponent",
                     "b.modification",
                     "b.cellularComponent",
                     "provider",
                     "comment")

recognized.idTypes <- c("entrezGeneID", "recon2ReactionID", "reconMetabolite");
